---

services:
  database:
    image: postgres:latest
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "dbpass"
      POSTGRES_DB: "store_db"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 128M
